src/integrations/integrations.json, src/integrations/phabricator.js
Phabricator is a suite of web-based software development collaboration tools.
Note: Though the `*://*.phacility.com/*` pattern should make the extension work on `https://test-mysite.phacility.com/` by default, I couldn't get it to work without adding a custom domain. I tested on two custom domains `https://test-mysite.phacility.com/` and `https://phabricator.mysite.com/` and it works as expected.
**screenshots:**
=> Add Phabricator integration

src/integrations/phabricator.js
Phabricator's integration uses the document URL to determine whether a Clockify button is needed or not. There are multiple URL patterns pointing to a single project board. Tags are also projects in Phabricator environment. 
This fix prevents duplicate Clockify buttons appearing on a card in a project board when reaching the board from different URL patterns.
=> fix phabricator integration with duplicate clockify icons

src/integrations/gitlab.js
Fixed button styling for Gitlab integration.
**Before:**
**After:**
=> Fixed button styling for Gitlab integration.

src/integrations/atlassian.js
Adjusted the clockify button to register on the issue that is currently in view, instead of the 'parent'-issue, also known as epic. This used to be the default behaviour, but after atlassian has changed their views, clockify has not been working as intended.
=> atlassian: clockify should take the lowest hierarchy issue number

package.json, webpack.config.js
closes #30
Also, minor note, but chrome official extension version is higher than the version here (1.7.5 vs 1.7.4).
For technical reference: https://webpack.js.org/guides/environment-variables/
=> Use webpack --env for powershell/cmd building support

src/integrations/atlassian.js
Fixes #33
It was found a few months ago that the Clockify button stopped appearing in Jira. Some time was taken to try to resolve any issues in the 4 main views to ensure the button would show in the correct place, with the correct issue number identified.
Work in this PR was tested in both Firefox and Chrome by using `debugger;` and inspecting what was found in all 4 issue views.
The main issue in Issue #33 was that `project` was not getting found before child nodes were accessed. I'm not fully clear on where it's trying to find a project, _but_ adding some checks before accessing child nodes resolved the error on my side.
After that was resolved, selectors and styles were updated to ensure the Clockify button was added in the correct place without breaking the UI. Additionally, some …
=> Resolve various issues to ensure buttons shows for Jira

src/application-types/extension.js, src/components/settings.component.js, src/helpers/integration-helper.js, src/helpers/project-helper.js, src/integrations/button.js, src/integrations/gitlab.js
Hi,
in our company we have an extensive use of gitlab issues. For our customers, we need to be able to easily calculate the number of hours spent on each issue.
Thus, we thought it would be best, if each issue in a project A matches a clockify task ind project A.
For now, the clockify browser plugin already matches the projects. We extended it, so that time is always tracked on a matching task.
Maybe this is something the community is interested in as well, so we created this PR to share it. If this does not find the way into master it is fine as well, we'd just use our own fork then.
PS: Thanks for creating such awesome software btw, it was really fun to extend.
PPS: We even did some more extensions (tag transfer from gitlab, billable settings), if this would be something you're …
=> Automatic assignment to tasks

src/integrations/integrations.json
Seems like this was accidentally removed in an earlier commit, this fixes it.
=> Add back the cerb integration to the list of integrations

src/integrations/button.js
Added possibility to pass a a full timeEntryOptions object to small button creation. This enables tasks and tags synchronization for small button, as requested here: https://github.com/clockify/browser-extension/pull/82#issuecomment-628779904
PS: Obviously the individual integrations will need to be changed to use that option. This PR merely gives them the option to do so.
=> Gitlab tasks small button

src/integrations/button.js, src/integrations/gitlab.js
Before #80 broke it, integrations were able to pass time entry description as function.
As I've noted in https://github.com/clockify/browser-extension/pull/82#issuecomment-630841085, this allows for dynamic evaluation of the properties at time of button click. As possible use case would be the following: If I am in an gitlab issue, change the tags of that issue and then start logging my time I want my new tag to be synced without reloading the page.
This PR fixes and generalizes this feature or all parameters, including for example the tags. I also took the freedom to remove the code duplication between normal and small button.
Finally, I implemented the aforementioned behavior for gitlab tags.
=> Button parameters as functions

src/application-types/extension.js, src/helpers/integration-helper.js, src/helpers/project-helper.js, src/integrations/button.js, src/integrations/gitlab.js, src/integrations/style.css
Hi,
besides #80 we actually implemented another extension to the plugin to make it more useful for our internal processes.
A demo says more than a thousand words: 
Basically, we found that often we forget clicking the time buttons, but were quite satisfied with the simplicity of gitlabs minimalistic time tracking, where you can just add durations like `1h 30m`. However, we cannot use gitblabs time tracking as it is always visible to everyone who has access to the issues and we did not have high hopes of changing that. So we implemented that feature into the clockify plugin.
This might be a feature specific to how we use time tracking. If this does not match your philosophy of time tracking, we'll just maintain our fork :)
However, if you are interested in this feature we might be able to …
=> Time inputs as addition to the time button

src/integrations/atlassian.js
This fixes an issue for the button created when the task is on the sidebar (on the backlog for example). In case a task was a subtask of another, it was taking the issue number of the parent instead of the child.
=> Wrong Jira issue number on sidebar

src/integrations/redmine.js
The button didn't show in Redmine issues. It was unnecessary to observe changes in DOM in Redmine.
=> Fix Redmine Integration

src/integrations/integrations.json
Azure Government has the the url of portal.azure.us
Office 365 has the url outlook.office365.com
Office 365 Gov has the following url outlook.office365.us
=> Support for Government Tenants and Office 365

src/integrations/azure.js
This enables you to create a custom field labeled "Clockify Project" for Work Items in Azure DevOps and set your Clockify Project there. If no "Clockify Project"-field exists, it will just use the regular project name like before. 
_I also did a minor fix to only select the correct element for the Clockify-button._
=> Azure DevOps - Project name from custom field & button element fix

src/integrations/taiga.js
I completely revamped the Taiga integration in different ways:
This implementation takes in consideration the project name and correctly sets it
Fixed some of the buttons that were not showing up (such as the issues list buttons)
Added a new type of button (Tasks list in User story details buttons)
made the buttons look nicer: the buttons now always display inline with the task name, and added spacing between the button and the task name
I only started using taiga recently but judging from the old code, taiga might have been updated in a breaking way for the integration, since there were some classes references that do not exist in Taiga nowadays, i have no means of testing if this change could break the integration on old Taiga versions
=> Updated Taiga integration

src/integrations/mantishub.js
Firefox integration of mantishub did not work with observer. So i disabled it.
Also added ability to pass mantishub project name to clockify.
=> Fixed : Mantishub integration on firefox do not work

src/integrations/github.js
Updates the GitHub integration, fixes #172 
I've manually tested this by building and loading the development extension for Chrome and then logging time via the dev extension into Clockify.
Unrelated: I noticed a missing dependency after `npm i` -- @hypnosphi/create-react-context. I also installed this to build the extension but I've left this out of the PR.
=> Fix repo name on GitHub repo

src/integrations/integrations.json, src/integrations/linear.js
As suggested here: https://forum.clockify.me/t/linear-app-chrome-extension-integration/1200/2, I'm working on adding integration for Linear.app but I ran into an issue. The `linear.js` is never injected into the DOM and I can't figure out why. I know my local setup is working correctly because I can run `npm run compile.dev.chrome`, refresh the chrome extension and I see console log statements that I've added to other integrations like Gitlab.
If I compare against some of the other integration PRs, I feel like what I have should be working. Can anyone point me in the right direction? 
Thank you for your time!
=> Linear.app Integration

src/integrations/zohodesk.js
The updated Zoho Desk UI had multiple instances of zd-ticketidcopy-ticketId in certain views. Updated this to zd-ticketsubject-ticketId to pull the correct ticket the end user is viewing.
=> Updated the const ticket value to fix a bug in the extension pulling the wrong value

src/integrations/generic-integration.js, src/integrations/integrations.json
This adds a generic integration that looks in any webpage for a DOM element having the class "clockify-container" and adds the clockify button to it. This allows any webpage to easily integrate clockify without the need of adding a custom integration to the browser extension. Espcially this would "allow for custom integrations without having to extend the extension" as requested in #58 (though by an alternative approach without GUI).
By adding data attributes to the placeholder DOM element one can controll the description, project, task, tags and whether the small version of the button shall be used. For example, the placeholder can be defined as follows:
`<div class="clockify-container" data-description="This is the description" data-project="My Project" data-task="Task 1" …
=> generic integration to integrate clockify in any webpage that includes a special placeholder

src/integrations/github.js, src/popupDlg/clockifyButton.js
Add noDebounce option to clockifyButton.render opts
Closes #201
I added the noDebounce option with this integration because clockifyDebounce was not allowing the proper document mutations to be detected. If no value is specified for tis option, the behavior will be the same as it was before this change.
=> Create integration for Github Projects

manifest.firefox.dev.json
The `background` permission is Chrome-specific and produces a warning when used in Firefox. The browser compatibility chart on MDN confirms this: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#browser_compatibility
=> Remove invalid permission from Firefox manifest

src/integrations/gitlab.js
Update the task name for Gitlab issues and MRs to be prefixed with the full GitLab reference (including group and project identifiers) instead of just the id number.
This matches the text used for cross-project references in Markdown on GitLab. See: https://docs.gitlab.com/ee/user/markdown.html#gitlab-specific-references
The table below summarizes the changes:
|Page Type|Old|New|
|-----------|----|-----|
|Issue|`#99 Issue Title`|`org-name/project-name#99 Issue Title`|
|MR|`MR99::Issue Title`|`org-name/project-name!99 Issue Title`|
This implements https://github.com/clockify/browser-extension/issues/24
=> Use GitLab reference identifiers in GitLab integration

src/integrations/todoist.js
If clockify button is pressed from the popup on todoist  website, it uses task name as clockify project name.
=> Fixed selector for todoist project name

src/integrations/azure.js
In the azure devOps integration the tags where incorrectly selected (and therefore not inserted).
The css class scopes the tag selection to the modal (or full page) work item shown.
Tested on chrome, firefox and edge
=> Azure Devops Integration: populate tags from Work Item

src/integrations/azure.js
Azure devOps is changing the way it displays work items (currently in preview as "New Board Hubs"). The tag retrieval was not working with the new version.
This change works with both the current version and the preview version.
=> get tags for Azure DevOps new Board Hub version

src/integrations/clickup.js
Fixes #249.
Since ClickUp 3.0, the task ID is missing from the description. Since the tab title has the description + task ID we can use that instead
=> Fixes missing task ID

src/integrations/integrations.json, src/integrations/pyrus.js
Added integration for pyrus.com:
Time entry description format: task name + task id (in parentheses).
Project name will be parsed from task name, as pyrus has no projects entity.
Example:
Task name: [test project] test task
Task id: 123
Result:
Time entity description: [test project] test task (#123)
Time entity project: test project
Tags will be parsed from task boards.
=> added pyrus.com integration

src/integrations/github.js
Implemented clockify small-button for GitHub's Project-perspective:
- Kanban
- Table
- "My Items"
- "Current Iteration"
Which by inference means it also now supports non-Issue tasks (GitHub's Project-pespective allows creation of tasks that are not tied to real GitHub Issues).
Also have code that enables pushing Labels from said tasks/issues, which works if Clockify already contains the associated Tag.
Let me know if any issues to help this PR along. 
I believe my code on line 33 might be one area of improvement. Am using a hard internal to access the local storage of the extension, to procure the list of projects - for loose comparison to the Github Project view's Project-Name.
This is because on project view, there is no other reference to the Repository, anywhere.
And React internals …
=> Feature/integration GitHub project perspective + drafts - 2024 09

src/integrations/fibery.js, src/integrations/integrations.json
This PR adds an integration with a new tool: Fibery, allowing users to track time directly in their task management tool.
I added both the time-tracking button and the time input on the Entity page under the Title.
- Tested on **Firefox** and **Chrome**
- Verified that the button was visible, clickable, and picking up the task title to populate the popup.
- Follow-ups would include other views (list, board, calendar, etc)
=> add fibery integration

src/integrations/linear.js
This PR modify the aria-label of the element being searched and modify the color of the button to match linear primary text color while inactive
Tested on Firefox and Chrome
Verified that the button was visible, clickable, and picking up the task title to populate the popup.
The popup has an issue with linear css variables
=> Update linear aria-label
