src/integrations/integrations.json, src/integrations/wekan.js
For wekan it's necessary add custom url
=> Add checklist wekan integration.

src/integrations/integrations.json, src/integrations/produck.js
[Produck](https://www.produck.io/) is a project management tool.
Google Chrome Demo:
Firefox Demo:
=> Add Produck integration

src/integrations/integrations.json, src/integrations/zammad.js
Hello,
Please find my working (tested) integration for zammad. I have styled it to fit in with the style of the software too.
=> zammad.com / zammad.org Helpdesk and Support Software Integration

src/integrations/atlassian.js
moved clockify button out of div so it won't interfere with the natie copy link
=> moved clockify button

src/integrations/infinity.js, src/integrations/integrations.json
Infinity Integration added to Clockify
=> added Infinity Integration

src/integrations/sentry.js
resolves https://github.com/clockify/browser-extension/issues/44
=> Fix Sentry selectors

src/integrations/atlassian.js
As requested here: https://github.com/clockify/browser-extension/issues/49
A pull request that fixes Jira integration.
=> added Jira integration (AUI layout?)

package-lock.json, src/integrations/helprace.js, src/integrations/integrations.json
We added support for use with Helprace. Our team has tested this internally and it is work.
=> Helprace addition

src/integrations/integrations.json, src/integrations/rallydev.js
New integration for rally1.rallydev.com/
=> integration for Rally

src/integrations/integrations.json, src/integrations/liveagent.js
Added clockify button to:
- ticket detail
- knowledgebase article dialog
Seems fine in all 4 agent panels themes.
Feel free to test it on some trial account https://www.liveagent.com/trial/.
=> LiveAgent integration

src/integrations/nela.js
Integration with the new layout
=> Add some other integrations with Nela

src/integrations/integrations.json, src/integrations/wikipedia.js
Probably useful for wiki's editors, also  it works in custom wikis
=> Wikipedia Integration Added

src/integrations/button.js
This should fix the issue mentioned here: https://github.com/clockify/browser-extension/pull/80#issuecomment-628653321
=> gitlab-tasks: fixed problem with small button

src/integrations/google-calendar.js
Added support for Task cards on Google Calendar.
Now when the user clicks on any task item on their calendar the start/stop timer button appears at the top left corner:
=> 🎁 Add support for Google Calendar Task cards

src/integrations/gitlab.js, src/integrations/redmine.js
I improved Redmine integration. Now the extension can select project and task. There is an input to add time also.
Additionally, I corrected Gitlab integration, because the extension had been picking the wrong elements on the page that resulted in errors.
=> Select project and task from Redmine and fix bugs in Gitlab

src/integrations/integrations.json, src/integrations/manageengine.js
Adding back the manage engine integration removed on the 27th May [release](https://github.com/clockify/browser-extension/commit/789f30208fcf81b335e737985dd4b0d0aaf119fe).
=> Added ManageEngine Integration back

src/integrations/integrations.json, src/integrations/usepixie.js
We have a number of accountancy firms asking us for the ability to track time in our product, and we'd like to recommend Clockify to them as a permanent solution.
=> Support for usepixie.com

src/integrations/freshrelease.js, src/integrations/integrations.json
Support for Freshrelease task tracker. There is already support for FreshWorks.
- Add timer button to agile board cards
- Add timer button to card details side modal
- Add timer button to card view page
=> Support for Freshrelease.com

src/integrations/usepixie.js
=> Update to usepixie.js

src/integrations/gitea.js, src/integrations/integrations.json, webpack.config.js
=> Gitea Integration

src/integrations/github.js
Currently i need to assign the tasks manually inside Clockify.
This fixes it.
Additionally an shown textbox for the description would be fine.
=> fixed: GitHub task integration

package.json, src/integrations/freshservice.js, src/integrations/integrations.json, src/integrations/style.css
Freshservice is a help-desk product in the FreshWorks family, alongside Freshdesk and Freshrelease.
CSS and package.json changes are explained in the commit messages.
=> Add freshservice integration

src/integrations/salesforce.js
Hi there, 
concerning https://github.com/clockify/browser-extension/issues/146 I went ahead and implemented it myself. Here is the pull request for it.
Regards
tim
=> Add id of salesforce object to description

src/integrations/hillia.js, src/integrations/integrations.json
Introduces integration for [https://www.hillia.app/](https://www.hillia.app/).
=> Add hillia.app integration

src/integrations/integrations.json, src/integrations/myfocusspace.js
Previously tested on Chrome and Firefox.
=> Add myfocusspace.com integration

src/integrations/usepixie.js
=> updated for new features in Pixie

src/integrations/integrations.json, src/integrations/zohodesk.js
Added integration for Zoho desk. This adds the clockify timer under the Due Date field of a ticket.
=> Integration for Zoho desk

src/integrations/monday.js
If a pulse is in a board named "Project: Task", then the clockify button on the pulse will start time tracking in the task. Also display the clockify tracking window on top of everything to allow adjustments and comments directly at tracking beginning.
=> Add task support for monday integration

src/integrations/dixa.js, src/integrations/integrations.json
This PR adds Dixa to the Clockify integrations. 
The integration have been tested ✅ 
Please see screenshot and recording below:
Thanks in advance!
=> feat(dixa): Implement Dixa integration

src/integrations/front.js, src/integrations/integrations.json
Add integration for Front. This adds the clockify timer button on the conversation header (on the right)
=> Add integration for Front

src/integrations/crowdin.js, src/integrations/integrations.json
Adds the tracker button to Crowdin, in the header of the translation editor where translators spend most of the time.
=> feat: adding Crowdin

src/integrations/integrations.json, src/integrations/kanbanize.js
Hi there. I'd like to add this integration for [Kanbanize](https://kanbanize.com/).
It adds the input field and button to the sidebar of the modal showing a ticket.
Please let me know if there's anything else to add or change.
=> Adds Kanbanize integration

src/integrations/conectohub.js, src/integrations/integrations.json
Added integration for ConectoHub. It adds Clockify into the task drawer.
https://www.conectohub.com/
=> Integration for ConectoHub

src/integrations/asana.js
Asana changed their class names again. This Pull Request makes the clockify extension work with the current version of Asana again.
=> Change Asana class names to make integration work again

src/integrations/integrations.json, src/integrations/teamwave.js
Hi there,
In this commit, i have added Teamwave integration, with the help of this start-stop Clockify timer button will appear in Teamwave's CRM and PM pages.
=> Teamwave_clockify_integration_v1.0

src/integrations/integrations.json, src/integrations/space.js
Support tracking time through issues on issue boards on Jetbrains Space
=> Jetbrains Space support

index.html, package.json, sass/_global.scss, webpack.config.js
Avoids loading fonts from google.
=> Bundle Roboto font

src/integrations/integrations.json, src/integrations/nifty.js
Added Nifty (nifty.pm) integration inside Task card
=> Adds Nifty integration

src/integrations/todoist.js
Fixes #240 
Remove section from project name on Todoist and also fix a description error I ran across on the same section. This was on the filters page. 
Let me know if this doesn't work.
=> Fix project name on Todoist Integration

.editorconfig, .gitignore, src/integrations/openproject.js
Added some improvements to OpenProject integration
1. Changed button location:
2. Changed Description format on `task 123: Title` that allows to use data with integrations and it is more readable: 
3. Added Clockify Task and Project mapping
and I included .editorconfig (+ vscode ignore files) because project's code style is different a little :)
=> OpenProject Integration improvements

src/integrations/github.js
=> Clockify button on github sidepanel issue details

src/integrations/kanbanize.js
Support added for cards without custom fields defined on Kanbanize integration, now appear clockify button on side on this cards
=> add support for card without custom fields defined on Kanbanize integration

sass/_settings.scss
This pull request addresses an issue with the user profile avatar style in the settings panel of the Clockify browser extension. The changes enhance the visual appearance of the avatar by making it more consistent and aesthetically pleasing.
- **Avatar Styling**: Applied `border-radius: 50%;` to make the avatar circular.
- **Image Fit**: Added `object-fit: cover;` to ensure the avatar image is properly cropped and fits within the circular frame.
- **Before**: The avatar image did not have a consistent shape and might have appeared stretched or out of place.
- **After**: The avatar image now appears as a perfect circle and maintains its proportions, providing a cleaner look.
- Verified that the avatar displays correctly in the settings panel.
- Ensured that the changes do not affect other …
=> [Styling] Fix User Avatar Style ✨

src/integrations/integrations.json, src/integrations/waywedo.js
Adds Way We Do integration to track time to complete a process or steps in a process.
=> Adds Way We Do integration
